### ISSUE TITLE
Mostrar 2 mensajes en vez de 1

### ISSUE THREAD

**Issue by josuemb** [josuemb/consoleapp1#12]
# Descripción
Mostrar mas de un mensaje.

**Mensajes**

```
void main() {
 printlln();
}
```

**Comment by josuemb** [comment]
> Descripción
> Mostrar mas de un mensaje.
> Mensajes
> void main() {
>  printlln();
> }

Yo NO estoy de acuerdo. <no me gusta

**Comment by josuemb** [comment]
esta relacionado con #8 

### Algo

**Comment by erramire** [comment]
No lo borres por favor @josuemb

**Comment by josuemb** [comment]
Duplicado de #8
